### PR TITLE
Convert and fix The Queen of Thorns (Core)

### LINKED ISSUE #1224: Queen of Thorns lets you drop 7 costers into play
As title really. Opponent was able to use Queen of Thorns to put Renly into play, but Queen has a restriction of 6 cost or lower.

### PR DESCRIPTION
**Pull request by DukeTax**
* Convert to use target API and only allow printed cost 6 or lower characters to be put into play.

* Fixes #1224.

### CODE REVIEW

**Comment by cryogen** [comment]
Can one of the admins verify this patch?

File: server/game/cards/characters/01/thequeenofthorns.js [hunk 1]
```diff
@@ -6,24 +6,17 @@ class TheQueenOfThorns extends DrawCard {
...
-            handler: () => {
-                this.game.promptForSelect(this.controller, {
-                    activePromptTitle: 'Select a character to put in play',
-                    source: this,
-                    cardCondition: card => card.location === 'hand' && card.getCost() && card.getType() === 'character' && card.isFaction('tyrell'),
-                    onSelect: (p, card) => this.onCardSelected(p, card)
-                });
+            target: {
+                activePromptTitle: 'Select a character to put into play',
+                cardCondition: card => card.location === 'hand' && card.controller === this.controller &&
```
Comment (zacchiro) [inline server/game/cards/characters/01/thequeenofthorns.js]: "card.controller === this.controller" shouldn't be needed, given the card is in hand, right?
I guess there could be bugs making that assumption false. But, in that case too, I'd rather not have the check because it will hide the bugs.

**Comment by cryogen** [comment]
Add to whitelist

File: server/game/cards/characters/01/thequeenofthorns.js (hunk 1 above)
Comment (DukeTax) [inline server/game/cards/characters/01/thequeenofthorns.js]: I'm not 100% sure, but wouldn't that allow you to target a card in an opponents hand (provided you happen to click one that pass the other conditions)? Or is that the opponent's hand not a legal target area anyway?

Comment (ystros) [inline server/game/cards/characters/01/thequeenofthorns.js]: There **may** be something client side that disallows clicking on facedown / hidden / opponent hand cards, but I'm not sure where it happens. We've also recently talked about being able to click opponent's hand cards as an alternate UI for things like His Viper Eyes and other "look at hand" abilities (e.g. make those cards not facedown and then do a normal card select prompt).

I don't think the controller check hurts anything here, but I'm not sure we've been consistent about it either.
